/**
 * Renders the charter and the pooling guide from Markdown into HTML for the
 * site, so the documents in the repository and the pages people read are
 * always the same words. Run with `npm run docs`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { marked } from 'marked';

const root = new URL('../', import.meta.url);
const OUTPUT = new URL('src/web/docs.generated.ts', root);
const SOURCE = 'https://github.com/3dprintit1/expleate/blob/HEAD/';

const SOURCES = {
  charter: 'CHARTER.md',
  pooling: 'docs/pooling.md',
} as const;

/** Links between documents become links between pages; links to code go to the repository. */
function siteLink(target: string): string {
  const clean = target.replace(/^(\.\.\/)+/, '').replace(/^\.\//, '');
  if (clean === 'CHARTER.md') return '/charter';
  if (clean === 'docs/pooling.md' || clean === 'pooling.md') return '/pooling';
  if (/^(src|test|docs|scripts)\//.test(clean) || clean.endsWith('.md')) return SOURCE + clean;
  return target;
}

function render(markdown: string): { title: string; html: string } {
  const title = /^#\s+(.+)$/m.exec(markdown)?.[1]?.trim() ?? 'Expleate';
  const linked = markdown.replace(/\]\(([^)\s]+)\)/g, (_, target: string) => `](${siteLink(target)})`);
  const html = marked.parse(linked, { async: false, gfm: true });
  return { title, html };
}

export function renderDocs(): string {
  const docs = Object.fromEntries(
    Object.entries(SOURCES).map(([key, path]) => [key, render(readFileSync(new URL(path, root), 'utf8'))]),
  );
  const body = Object.entries(docs)
    .map(([key, doc]) => `  ${key}: {\n    title: ${JSON.stringify(doc.title)},\n    html: ${JSON.stringify(doc.html)},\n  },`)
    .join('\n');
  return [
    '// Generated by scripts/build-docs.ts from CHARTER.md and docs/pooling.md.',
    '// Please edit the Markdown instead, then run `npm run docs`.',
    '',
    'export const DOCS = {',
    body,
    '} as const;',
    '',
  ].join('\n');
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  writeFileSync(OUTPUT, renderDocs());
  console.log(`Wrote ${fileURLToPath(OUTPUT)}`);
}
